# 01 - Data Understanding
**Project:** Air Quality & Pollution Intelligence - Data Mining and Business Intelligence

**Objective:** Inspect the real dataset before writing any analysis code: shape, columns, types, missing values, duplicates, cities, date range, and a data dictionary.

**How to read this notebook:** every number printed below is produced by the
code in this notebook from `data/raw/Air_quality_data.csv`. Column names are
discovered at runtime through `src/config.py`, so nothing is assumed.

In [1]:
"""Environment bootstrap: make src/ importable and pin the working directory."""
import sys, os, warnings
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(PROJECT_ROOT / "src"))
os.chdir(PROJECT_ROOT)
warnings.filterwarnings("ignore", category=FutureWarning)
pd.set_option("display.width", 200)
pd.set_option("display.max_columns", 60)
pd.set_option("display.max_colwidth", 90)
%matplotlib inline
print("project root:", PROJECT_ROOT)

project root: C:\Users\DELL\OneDrive\Desktop\Air Quality

## 1. Load the raw file (read-only)

The raw dataset is never modified. `src/data_utils.load_raw()` accepts either
`Air_quality_data.csv` (the uploaded file) or `city_day.csv` (the name under
which this Kaggle dataset is usually published).

In [2]:
import config as C
import data_utils as U

raw = U.load_raw()
print("file            :", C.RAW_FILE.name)
print("rows            :", f"{raw.shape[0]:,}")
print("columns         :", raw.shape[1])
print("column names    :", list(raw.columns))

file            : Air_quality_data.csv
rows            : 18,265
columns         : 13
column names    : ['City', 'Datetime', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3', 'AQI', 'AQI_Bucket']

## 2. First and last records

In [3]:
display(raw.head())
display(raw.tail())

        City    Datetime  PM2.5   PM10     NO   NO2    NOx   NH3    CO   SO2     O3    AQI AQI_Bucket
0      Delhi  2015-01-01  153.3  241.7  182.9  33.0   81.3  38.5  1.87  64.5   83.6  325.8  Very Poor
1     Mumbai  2015-01-01   70.5  312.7  195.0  42.0  122.5  31.5  7.22  83.8  108.0  262.7       Poor
2    Chennai  2015-01-01  174.1  275.4   56.2  68.8  230.9  28.5  8.56  60.8   43.9  341.8  Very Poor
3    Kolkata  2015-01-01  477.2  543.9   14.1  76.4  225.9  45.6  2.41  42.1  171.1  206.3       Poor
4  Bangalore  2015-01-01  171.6  117.7  123.3  12.4   61.9  49.7  1.26  79.7  164.3  339.8  Very Poor

            City    Datetime  PM2.5   PM10     NO    NO2    NOx   NH3    CO   SO2     O3    AQI AQI_Bucket
18260      Delhi  2024-12-31  371.2   61.7   14.6  130.7  159.1  45.9  7.02  76.4   40.0  162.7   Moderate
18261     Mumbai  2024-12-31  180.2  259.3  181.9   50.7  135.7  22.4  8.85  12.2  147.3  346.4  Very Poor
18262    Chennai  2024-12-31  188.6  434.4   68.8  126.1  142.7  47.0  8.30  50.2  128.6  405.9     Severe
18263    Kolkata  2024-12-31  343.0  458.6  106.7  108.3  137.8  22.6  2.11  71.4  175.8  493.0     Severe
18264  Bangalore  2024-12-31  121.9  100.0   37.7  118.5  224.8  32.6  9.89  16.9   62.6  301.7  Very Poor

## 3. Data types and memory

In [4]:
raw.info()
print()
raw.dtypes

<class 'pandas.DataFrame'>
RangeIndex: 18265 entries, 0 to 18264
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        18265 non-null  str
 1   Datetime    18265 non-null  str
 2   PM2.5       18265 non-null  float64
 3   PM10        18265 non-null  float64
 4   NO          18265 non-null  float64
 5   NO2         18265 non-null  float64
 6   NOx         18265 non-null  float64
 7   NH3         18265 non-null  float64
 8   CO          18265 non-null  float64
 9   SO2         18265 non-null  float64
 10  O3          18265 non-null  float64
 11  AQI         18265 non-null  float64
 12  AQI_Bucket  18265 non-null  str
dtypes: float64(10), str(3)
memory usage: 1.8 MB

City              str
Datetime          str
PM2.5         float64
PM10          float64
NO            float64
NO2           float64
NOx           float64
NH3           float64
CO            float64
SO2           float64
O3            float64
AQI           float64
AQI_Bucket        str
dtype: object

## 4. Summary statistics for every column (numeric and categorical)

In [5]:
raw.describe(include="all").T

              count unique         top  freq        mean         std   min    25%    50%    75%    max
City          18265      5       Delhi  3653         NaN         NaN   NaN    NaN    NaN    NaN    NaN
Datetime      18265   3653  2015-01-01     5         NaN         NaN   NaN    NaN    NaN    NaN    NaN
PM2.5       18265.0    NaN         NaN   NaN  250.597695  144.460292   0.0  125.7  251.0  376.2  499.9
PM10        18265.0    NaN         NaN   NaN  299.442491  173.479906   0.0  150.1  300.3  450.0  600.0
NO          18265.0    NaN         NaN   NaN  100.481035   57.774795   0.0   50.6  100.2  151.0  200.0
NO2         18265.0    NaN         NaN   NaN   75.415916   43.460066   0.0   37.7   76.0  113.2  150.0
NOx         18265.0    NaN         NaN   NaN  125.964079   72.403893   0.0   63.1  126.2  188.9  250.0
NH3         18265.0    NaN         NaN   NaN   25.065042   14.452019   0.0   12.6   25.3   37.6   50.0
CO          18265.0    NaN         NaN   NaN    5.002451    2.889439   0.0   2.49    5.0   7.51   10.0
SO2         18265.0    NaN         NaN   NaN   49.835839   28.988739   0.0   24.4   49.9   75.1  100.0
O3          18265.0    NaN         NaN   NaN   100.40674   57.591436   0.0   50.6  100.7  150.4  200.0
AQI         18265.0    NaN         NaN   NaN  317.505212  113.894816  26.9  207.1  331.6  414.0  500.0
AQI_Bucket    18265      6   Very Poor  5501         NaN         NaN   NaN    NaN    NaN    NaN    NaN

## 5. Per-column profile produced by the project code

`Missing`, `Unique`, range and a negative-value count per column. The
negative-value column is the first validity check: a concentration cannot be
below zero.

In [6]:
prof = U.profile(raw)
prof

        Column    Dtype  NonNull  Missing  Missing_Pct  Unique         Min         Max     Mean Median  Negative_Values
0         City      str    18265        0          0.0       5         NaN         NaN      NaN    NaN                0
1     Datetime      str    18265        0          0.0    3653  2015-01-01  2024-12-31      NaN    NaN                0
2        PM2.5  float64    18265        0          0.0    4876         0.0       499.9  250.598  251.0                0
3         PM10  float64    18265        0          0.0    5709         0.0       600.0  299.442  300.3                0
4           NO  float64    18265        0          0.0    2000         0.0       200.0  100.481  100.2                0
5          NO2  float64    18265        0          0.0    1501         0.0       150.0   75.416   76.0                0
6          NOx  float64    18265        0          0.0    2498         0.0       250.0  125.964  126.2                0
7          NH3  float64    18265        0          0.0     501         0.0        50.0   25.065   25.3                0
8           CO  float64    18265        0          0.0    1001         0.0        10.0    5.002    5.0                0
9          SO2  float64    18265        0          0.0    1001         0.0       100.0   49.836   49.9                0
10          O3  float64    18265        0          0.0    2001         0.0       200.0  100.407  100.7                0
11         AQI  float64    18265        0          0.0    3848        26.9       500.0  317.505  331.6                0
12  AQI_Bucket      str    18265        0          0.0       6         NaN         NaN      NaN    NaN                0

## 6. Missing values

In [7]:
miss = U.missing_table(raw)
print("cells that are missing:", int(raw.isna().sum().sum()))
miss if len(miss) else "No missing values in any column - verified, not assumed."

cells that are missing: 0

'No missing values in any column - verified, not assumed.'

## 7. Duplicate records

Two different checks: fully identical rows, and repeated City + Date keys (a city should be measured once per day).

In [8]:
import pandas as pd
date_col = C.date_column(raw.columns)
print("exact duplicate rows          :", int(raw.duplicated().sum()))
print(f"duplicate ({C.CITY_COL}, {date_col}) keys:",
      int(raw.duplicated(subset=[C.CITY_COL, date_col]).sum()))

exact duplicate rows          : 0
duplicate (City, Datetime) keys: 0

## 8. Cities and date range

In [9]:
print("unique cities:", raw[C.CITY_COL].nunique())
display(raw[C.CITY_COL].value_counts().rename("observations").to_frame())

dates = pd.to_datetime(raw[date_col], errors="coerce")
print("earliest observation :", dates.min().date())
print("latest observation   :", dates.max().date())
print("unparseable dates    :", int(dates.isna().sum()))
print("calendar days per city (expect equal counts for a balanced panel):")
display(raw.groupby(C.CITY_COL)[date_col].nunique().rename("distinct dates"))

unique cities: 5

           observations
City
Delhi              3653
Mumbai             3653
Chennai            3653
Kolkata            3653
Bangalore          3653

earliest observation : 2015-01-01
latest observation   : 2024-12-31
unparseable dates    : 0
calendar days per city (expect equal counts for a balanced panel):

City
Bangalore    3653
Chennai      3653
Delhi        3653
Kolkata      3653
Mumbai       3653
Name: distinct dates, dtype: int64

### Is the panel complete?

A balanced daily panel should contain (number of days in the range) x (number of
cities) rows. The cell below checks it, because gaps change how time-series
results must be interpreted.

In [10]:
expected_days = (dates.max().normalize() - dates.min().normalize()).days + 1
per_city = raw.groupby(C.CITY_COL)[date_col].nunique()
print(f"days in calendar range      : {expected_days}")
print(f"dates observed per city     : {sorted(per_city.unique())}")
print(f"expected rows if balanced   : {expected_days * raw[C.CITY_COL].nunique():,}")
print(f"actual rows                 : {len(raw):,}")
print("panel is complete           :", expected_days * raw[C.CITY_COL].nunique() == len(raw))

days in calendar range      : 3653
dates observed per city     : [np.int64(3653)]
expected rows if balanced   : 18,265
actual rows                 : 18,265
panel is complete           : True

## 9. AQI categories present in the data

In [11]:
if C.TARGET_COL in raw.columns:
    b = raw[C.TARGET_COL].value_counts(dropna=False).rename("observations").to_frame()
    b["percent"] = (100 * b["observations"] / b["observations"].sum()).round(2)
    display(b)
    print("distinct categories:", int(raw[C.TARGET_COL].nunique()))
if C.AQI_COL in raw.columns:
    print("AQI numeric range :", raw[C.AQI_COL].min(), "to", raw[C.AQI_COL].max())

              observations  percent
AQI_Bucket
Very Poor             5501    30.12
Severe                5258    28.79
Moderate              4258    23.31
Poor                  3129    17.13
Satisfactory           113     0.62
Good                     6     0.03

distinct categories: 6
AQI numeric range : 26.9 to 500.0

## 10. Data dictionary

Generated from the columns that actually exist. Any column not documented by
the source is labelled as such rather than given an invented meaning.

In [12]:
dictionary = U.data_dictionary(raw)
dictionary

        Column                     Type                                              Description  Missing Values  Missing %  Unique
0         City              Categorical                        Name of the monitored Indian city               0        0.0       5
1     Datetime  Date (text in raw file)                          Observation date (daily record)               0        0.0    3653
2        PM2.5                  Numeric           Fine particulate matter ≤ 2.5 µm concentration               0        0.0    4876
3         PM10                  Numeric       Inhalable particulate matter ≤ 10 µm concentration               0        0.0    5709
4           NO                  Numeric                               Nitric oxide concentration               0        0.0    2000
5          NO2                  Numeric                           Nitrogen dioxide concentration               0        0.0    1501
6          NOx                  Numeric                      Total nitrogen oxides concentration               0        0.0    2498
7          NH3                  Numeric                                    Ammonia concentration               0        0.0     501
8           CO                  Numeric                            Carbon monoxide concentration               0        0.0    1001
9          SO2                  Numeric                            Sulphur dioxide concentration               0        0.0    1001
10          O3                  Numeric                                      Ozone concentration               0        0.0    2001
11         AQI                  Numeric             Air Quality Index as supplied by the dataset               0        0.0    3848
12  AQI_Bucket              Categorical  Categorical AQI band derived from AQI by the data owner               0        0.0       6

## 11. Schema reconciliation against the expected Kaggle schema

The project brief listed an expected schema. The columns that are missing here
are reported explicitly; the analysis is then restricted to what exists. No
column is invented.

In [13]:
expected = ["City", "Date", "PM2.5", "PM10", "NO", "NO2", "NOx", "NH3",
          "CO", "SO2", "O3", "Benzene", "Toluene", "Xylene", "AQI", "AQI_Bucket"]
actual = [str(c) for c in raw.columns]
present_in_place_of_date = "Datetime" if "Datetime" in actual else "Date"
matched = [e for e in expected if e in actual] + (
    ["Date (supplied as 'Datetime')"] if present_in_place_of_date == "Datetime" else [])
missing = [e for e in expected if e not in actual and e != "Date"]
extra = [a for a in actual if a not in expected and a != "Datetime"]
print("expected but present under another name :",
      ["Date -> Datetime"] if "Datetime" in actual else [])
print("expected but NOT in this dataset        :", missing)
print("present but not in the expected list    :", extra)
print("pollutants actually analysed            :", C.pollutant_columns(raw.columns))
print()
print("Decision: the three hydrocarbon columns (Benzene, Toluene, Xylene) are")
print("absent, so they are excluded from EDA, clustering and classification.")

expected but present under another name : ['Date -> Datetime']
expected but NOT in this dataset        : ['Benzene', 'Toluene', 'Xylene']
present but not in the expected list    : []
pollutants actually analysed            : ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3']

Decision: the three hydrocarbon columns (Benzene, Toluene, Xylene) are
absent, so they are excluded from EDA, clustering and classification.

## 12. Headline data-quality report (saved)

This is the table that is reused in the final report.

In [14]:
import json
summary = U.summary(raw)
display(pd.DataFrame(list(summary.items()), columns=["Metric", "Value"]))
C.PROCESSED_DIR.mkdir(exist_ok=True, parents=True)
dictionary.to_csv(C.PROCESSED_DIR / "data_dictionary.csv", index=False)
prof.to_csv(C.PROCESSED_DIR / "raw_column_profile.csv", index=False)
(C.PROCESSED_DIR / "understanding_summary.json").write_text(
    json.dumps(summary, indent=2, default=str), encoding="utf-8")
print("saved: data/processed/data_dictionary.csv, raw_column_profile.csv,")
print("       understanding_summary.json")

                        Metric                                        Value
0                   Total Rows                                        18265
1                Total Columns                                           13
2               Duplicate Rows                                            0
3         Total Missing Values                                            0
4         Columns With Missing                                            0
5                Unique Cities                                            5
6                  Date Column                                     Datetime
7                   Date Start                                   2015-01-01
8                     Date End                                   2024-12-31
9            Numerical Columns                                           10
10         Categorical Columns                                            3
11  Pollutant Columns Detected                                            9
12                  Pollutants  PM2.5, PM10, NO, NO2, NOx, NH3, CO, SO2, O3
13          AQI Column Present                                         True
14   AQI_Bucket Column Present                                         True

saved: data/processed/data_dictionary.csv, raw_column_profile.csv,
       understanding_summary.json

## Verification checklist for this stage

- [x] File loads without error
- [x] Row/column counts printed from the object, not typed in
- [x] Every column's type shown
- [x] Missing-value counts computed per column
- [x] Duplicate rows checked (exact and key-based)
- [x] City list and date range verified
- [x] Panel completeness verified against the calendar
- [x] Differences from the expected schema documented

**Common errors and what they mean**

| Error | Meaning | Fix |
|---|---|---|
| `FileNotFoundError: data/raw/...` | Notebook run from the wrong folder | The bootstrap cell changes to the project root; re-run it |
| `KeyError: 'Date'` | This file names the column `Datetime` | `C.date_column()` already resolves it - use it instead of a literal |
| `ModuleNotFoundError: config` | `src/` not on the path | Re-run the bootstrap cell |

**Next:** `02_data_cleaning.ipynb`.